# Generated by Django 3.2.22 on 2023-11-12 14:38

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=movies.models.uniq_name_upload)),
                ('trailer_url', models.URLField()),
                ('title_ru', models.CharField(max_length=255)),
                ('title_orig', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publish_year', models.IntegerField()),
                ('timing', models.IntegerField()),
                ('premier_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.genre')),
            ],
        ),
    ]
